#!/usr/bin/env python3
"""
Refresh Google Scholar citation counts for entries in _data/publications.yml.

Output goes to _data/scholar_counts.yml, which Jekyll inlines into
window.SCHOLAR_COUNTS on /publications/. The site prefers Scholar counts
when present and falls back to OpenAlex for the rest (see assets/js/research.js).

Usage (from project root):

    # First-time setup
    python3 -m venv .venv-scholar
    .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt

    # Refresh
    .venv-scholar/bin/python scripts/fetch_scholar_counts.py

    # Useful flags
    --limit N         Only attempt first N publications (smoke test)
    --only DOI        Only attempt a single DOI
    --dry-run         Fetch but don't write the YAML
    --no-jitter       Disable the 15-45 s sleep (DO NOT use weekly — Scholar
                      will block your IP)

Run locally on a residential IP. GitHub Actions IPs are blocklisted by Scholar.

DOI normalization
-----------------
All DOI keys in the output file are lowercased and stripped of any leading
https?://doi.org/ prefix. The JS reader (assets/js/research.js) applies the
same normalization. MISQ DOIs (e.g. 10.25300/MISQ/2022/16959) are mixed-case
in publications.yml but DOI is case-insensitive per spec — lowercasing both
sides keeps the lookup chain self-consistent.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import random
import re
import string
import sys
import tempfile
import time
from difflib import SequenceMatcher
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing. Run: .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt")

try:
    from scholarly import scholarly
    from scholarly._navigator import MaxTriesExceededException
except ImportError:
    sys.exit("scholarly missing. Run: .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt")


ROOT = Path(__file__).resolve().parent.parent
PUBS_FILE = ROOT / "_data" / "publications.yml"
OUT_FILE = ROOT / "_data" / "scholar_counts.yml"


def normalize_doi(doi: str) -> str:
    doi = (doi or "").strip()
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi, flags=re.IGNORECASE)
    return doi.lower()


def normalize_title(title: str) -> str:
    """Lowercase, strip punctuation and collapse whitespace for similarity comparison."""
    title = (title or "").lower()
    title = title.translate(str.maketrans("", "", string.punctuation))
    title = re.sub(r"\s+", " ", title).strip()
    return title


def title_ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, normalize_title(a), normalize_title(b)).ratio()


def first_author_last_name(authors: list[str]) -> str:
    """Authors are stored as "Last F" (sometimes with bold markdown around Kevin)."""
    if not authors:
        return ""
    first = authors[0].replace("**", "").strip()
    # "Last F" → "Last"
    return first.split()[0]


def load_existing() -> dict:
    if OUT_FILE.exists():
        with OUT_FILE.open() as f:
            data = yaml.safe_load(f) or {}
        return data
    return {}


def atomic_write_yaml(payload: dict) -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=str(OUT_FILE.parent),
        prefix=".scholar_counts.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(
            "# Auto-generated by scripts/fetch_scholar_counts.py. Edit via the script, not by hand.\n"
        )
        yaml.safe_dump(
            payload,
            tmp,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=120,
        )
        tmp_path = tmp.name
    os.replace(tmp_path, OUT_FILE)


def verify_match(our_title: str, our_year: int, our_doi: str, scholar_pub: dict) -> tuple[bool, str, float]:
    """
    Returns (is_match, reason, title_similarity).

    Three checks, all must pass:
      - DOI cross-check when Scholar provides one
      - Title similarity (tiered threshold by word count)
      - Year within ±1
    """
    bib = scholar_pub.get("bib", {}) or {}
    s_title = bib.get("title", "") or ""
    s_year = bib.get("pub_year") or bib.get("year")
    s_doi = bib.get("doi", "") or ""

    sim = title_ratio(our_title, s_title)

    # DOI cross-check (hard mismatch wins)
    if s_doi:
        if normalize_doi(s_doi) != normalize_doi(our_doi):
            return False, f"doi-mismatch (scholar={s_doi!r})", sim

    # Title similarity threshold (tiered)
    word_count = len(our_title.split())
    threshold = 0.92 if word_count < 8 else 0.85
    if sim < threshold:
        return False, f"title-similarity {sim:.2f} < {threshold:.2f} (got {s_title!r})", sim

    # Year proximity
    try:
        s_year_int = int(s_year)
        if abs(s_year_int - int(our_year)) > 1:
            return False, f"year {s_year_int} ≠ {our_year} ±1", sim
    except (TypeError, ValueError):
        # Some Scholar results have no year — accept if title+DOI checks passed
        pass

    return True, "ok", sim


def scrape(args) -> int:
    with PUBS_FILE.open() as f:
        pubs = yaml.safe_load(f) or []

    existing = load_existing()
    counts = dict(existing.get("counts") or {})

    if args.only:
        target_doi = normalize_doi(args.only)
        pubs = [p for p in pubs if normalize_doi(p.get("doi", "")) == target_doi]
        if not pubs:
            sys.exit(f"No publication in {PUBS_FILE.name} matches --only {args.only}")

    if args.limit:
        pubs = pubs[: args.limit]

    n_updated = n_unchanged = n_skipped = n_failed = 0
    blocked = False

    for i, pub in enumerate(pubs):
        doi_raw = pub.get("doi", "")
        doi = normalize_doi(doi_raw)
        title = pub.get("title", "")
        year = pub.get("year")

        if not doi:
            print(f"[skip] (no DOI)                              {title[:60]}")
            n_skipped += 1
            continue

        # Forthcoming papers ARE attempted: working-paper cites are exactly
        # where Scholar > OpenAlex. The verify_match() guard (title sim + year
        # ±1 + DOI cross-check) is strict enough to reject wrong matches.

        author_last = first_author_last_name(pub.get("authors", []))
        query = f"{title} {author_last}".strip()

        try:
            results = scholarly.search_pubs(query)
            first = next(results, None)
        except MaxTriesExceededException:
            print(f"[BLOCKED] Scholar blocked the IP at paper #{i+1} ({doi}).")
            print(f"          {n_updated} updated, {n_unchanged} unchanged before block.")
            print(f"          Wait 24h or switch networks and re-run.")
            blocked = True
            break
        except Exception as e:
            print(f"[fail] {doi:<40} ({type(e).__name__}: {e})")
            n_failed += 1
            continue

        if first is None:
            print(f"[fail] {doi:<40} (no Scholar results)")
            n_failed += 1
        else:
            ok, reason, sim = verify_match(title, year, doi, first)
            if not ok:
                print(f"[fail] {doi:<40} ({reason})")
                n_failed += 1
            else:
                new_count = first.get("num_citations")
                if new_count is None:
                    print(f"[fail] {doi:<40} (no num_citations field)")
                    n_failed += 1
                else:
                    old = counts.get(doi, {}).get("count") if isinstance(counts.get(doi), dict) else None
                    arrow = f"{old} → {new_count}" if old is not None else f"{new_count}"
                    print(f"[ok]   {doi:<40} {arrow}   (match {sim:.2f})")
                    counts[doi] = {"count": int(new_count), "title_match": round(sim, 3)}
                    if old == new_count:
                        n_unchanged += 1
                    else:
                        n_updated += 1

        # Persist after every paper, regardless of outcome — protects against block mid-run.
        if not args.dry_run and i < len(pubs) - 1:
            payload = {
                "fetched_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
                "source": "google_scholar (via scholarly)",
                "counts": counts,
            }
            atomic_write_yaml(payload)

        # Jitter (skip on the last paper)
        if not args.no_jitter and i < len(pubs) - 1:
            delay = random.uniform(15, 45)
            time.sleep(delay)

    # Final write
    if not args.dry_run:
        payload = {
            "fetched_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
            "source": "google_scholar (via scholarly)",
            "counts": counts,
        }
        atomic_write_yaml(payload)
        print(f"\nWrote {OUT_FILE.relative_to(ROOT)}")

    print(
        f"\nSummary: {n_updated} updated, {n_unchanged} unchanged, "
        f"{n_skipped} skipped, {n_failed} failed."
    )
    if blocked:
        print("Run was interrupted by a Scholar block; partial progress preserved.")
        return 2
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, help="Only attempt first N publications.")
    ap.add_argument("--only", type=str, help="Only attempt a single DOI.")
    ap.add_argument("--dry-run", action="store_true", help="Fetch but don't write.")
    ap.add_argument("--no-jitter", action="store_true", help="Disable 15-45 s sleep (debugging only).")
    args = ap.parse_args()

    if not PUBS_FILE.exists():
        sys.exit(f"Missing {PUBS_FILE}")

    raise SystemExit(scrape(args))


if __name__ == "__main__":
    main()
