#!/usr/bin/env python3
"""
Refresh Google Scholar citation counts for entries in _data/publications.yml.

Output goes to _data/scholar_counts.yml, which Jekyll inlines into
window.SCHOLAR_COUNTS on /publications/. The site prefers Scholar counts
when present and falls back to OpenAlex for the rest (see assets/js/research.js).

Usage (from project root):

    # First-time setup
    python3 -m venv .venv-scholar
    .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt

    # Refresh
    .venv-scholar/bin/python scripts/fetch_scholar_counts.py

    # Useful flags
    --limit N         Only attempt first N publications (smoke test)
    --only DOI        Only attempt a single DOI
    --dry-run         Fetch but don't write the YAML
    --no-jitter       Disable the 15-45 s sleep (DO NOT use weekly — Scholar
                      will block your IP)

Run locally on a residential IP. GitHub Actions IPs are blocklisted by Scholar.

DOI normalization
-----------------
All DOI keys in the output file are lowercased and stripped of any leading
https?://doi.org/ prefix. The JS reader (assets/js/research.js) applies the
same normalization. MISQ DOIs (e.g. 10.25300/MISQ/2022/16959) are mixed-case
in publications.yml but DOI is case-insensitive per spec — lowercasing both
sides keeps the lookup chain self-consistent.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import random
import re
import string
import sys
import tempfile
import time
from difflib import SequenceMatcher
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing. Run: .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt")

try:
    from scholarly import scholarly
    from scholarly._navigator import MaxTriesExceededException
except ImportError:
    sys.exit("scholarly missing. Run: .venv-scholar/bin/pip install -r scripts/requirements-scholar.txt")


ROOT = Path(__file__).resolve().parent.parent
PUBS_FILE = ROOT / "_data" / "publications.yml"
OUT_FILE = ROOT / "_data" / "scholar_counts.yml"

# How many of Scholar's top hits to consider per paper before giving up.
# Scholar occasionally surfaces a junk stub (PDF-parse artifact, no year/DOI,
# 0 cites) ahead of the real entry, e.g. 10.25300/MISQ/2018/14105. Walking
# past failing hits to find a real verify_match() pass costs no extra HTTP
# requests (all within the same result page).
MAX_SCHOLAR_HITS = 5

# Jitter range (seconds) between papers. Conservative enough that 39-paper
# runs don't reliably hit Scholar's rate limit. Bumped from 15-45s after
# observing a block at paper #39/39 — the cumulative request rate matters
# more than the per-request spacing, so longer mean delay reduces block
# probability on full refreshes.
JITTER_MIN_SEC = 30
JITTER_MAX_SEC = 90

# Default freshness threshold: a paper whose count was successfully fetched
# within the last N days is skipped on the next run. Combined with the
# always-retry-flagged behaviour, this makes restart-after-block essentially
# free — only the unfetched + flagged subset is re-queried.
DEFAULT_MAX_AGE_DAYS = 7


def normalize_doi(doi: str) -> str:
    doi = (doi or "").strip()
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi, flags=re.IGNORECASE)
    return doi.lower()


def normalize_title(title: str) -> str:
    """Lowercase, strip punctuation and collapse whitespace for similarity comparison."""
    title = (title or "").lower()
    title = title.translate(str.maketrans("", "", string.punctuation))
    title = re.sub(r"\s+", " ", title).strip()
    return title


def title_ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, normalize_title(a), normalize_title(b)).ratio()


def first_author_last_name(authors: list[str]) -> str:
    """Authors are stored as "Last F" (sometimes with bold markdown around Kevin)."""
    if not authors:
        return ""
    first = authors[0].replace("**", "").strip()
    # "Last F" → "Last"
    return first.split()[0]


def load_existing() -> dict:
    if OUT_FILE.exists():
        with OUT_FILE.open() as f:
            data = yaml.safe_load(f) or {}
        return data
    return {}


def atomic_write_yaml(payload: dict) -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=str(OUT_FILE.parent),
        prefix=".scholar_counts.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(
            "# Auto-generated by scripts/fetch_scholar_counts.py. Edit via the script, not by hand.\n"
        )
        yaml.safe_dump(
            payload,
            tmp,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=120,
        )
        tmp_path = tmp.name
    os.replace(tmp_path, OUT_FILE)


def verify_match(our_title: str, our_year: int, our_doi: str, scholar_pub: dict) -> tuple[bool, str, float]:
    """
    Returns (is_match, reason, title_similarity).

    Title similarity is necessary. Beyond that we require at least ONE
    positive identity confirmation — either DOI or year. Title alone is not
    enough because Scholar occasionally returns metadata-poor stubs (e.g.
    PDF-parse artifacts where author=['IV Regression'], year='NA', doi='')
    that match the title perfectly but represent a junk entry with 0 cites
    rather than the real published version.
    """
    bib = scholar_pub.get("bib", {}) or {}
    s_title = bib.get("title", "") or ""
    s_year = bib.get("pub_year") or bib.get("year")
    s_doi = bib.get("doi", "") or ""

    sim = title_ratio(our_title, s_title)

    # Title similarity threshold (tiered)
    word_count = len(our_title.split())
    threshold = 0.92 if word_count < 8 else 0.85
    if sim < threshold:
        return False, f"title-similarity {sim:.2f} < {threshold:.2f} (got {s_title!r})", sim

    # DOI cross-check: hard mismatch wins; matching DOI is positive ID.
    doi_confirmed = False
    if s_doi:
        if normalize_doi(s_doi) != normalize_doi(our_doi):
            return False, f"doi-mismatch (scholar={s_doi!r})", sim
        doi_confirmed = True

    # Year proximity: hard mismatch wins; matching year is positive ID.
    year_confirmed = False
    try:
        s_year_int = int(s_year)
        if abs(s_year_int - int(our_year)) > 1:
            return False, f"year {s_year_int} ≠ {our_year} ±1", sim
        year_confirmed = True
    except (TypeError, ValueError):
        pass

    # Require at least one positive ID. Title alone is insufficient — see
    # docstring for the false-positive case this guards against.
    if not (doi_confirmed or year_confirmed):
        return False, "metadata-poor entry (no year/DOI to confirm match)", sim

    return True, "ok", sim


def build_payload(counts: dict, flagged: dict) -> dict:
    # Sort by DOI for deterministic diffs regardless of iteration order
    # (we shuffle the iteration order to spread block risk across runs).
    sorted_counts = {k: counts[k] for k in sorted(counts)}
    payload = {
        "fetched_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "source": "google_scholar (via scholarly)",
        "counts": sorted_counts,
    }
    if flagged:
        payload["flagged_for_review"] = {k: flagged[k] for k in sorted(flagged)}
    return payload


def scrape(args) -> int:
    with PUBS_FILE.open() as f:
        pubs = yaml.safe_load(f) or []

    existing = load_existing()
    counts = dict(existing.get("counts") or {})
    # flagged_for_review: { doi: "reason string" } — preserved across runs,
    # cleared when a DOI later succeeds with a non-zero count.
    flagged_raw = existing.get("flagged_for_review") or {}
    flagged = dict(flagged_raw) if isinstance(flagged_raw, dict) else {}

    # Backfill per-entry fetched_at from the top-level value if missing
    # (migrates older scholar_counts.yml files that pre-date per-entry timestamps).
    top_fetched_at = existing.get("fetched_at") or ""
    for entry in counts.values():
        if isinstance(entry, dict) and "fetched_at" not in entry and top_fetched_at:
            entry["fetched_at"] = top_fetched_at

    if args.only:
        target_doi = normalize_doi(args.only)
        pubs = [p for p in pubs if normalize_doi(p.get("doi", "")) == target_doi]
        if not pubs:
            sys.exit(f"No publication in {PUBS_FILE.name} matches --only {args.only}")

    if args.limit:
        pubs = pubs[: args.limit]
    elif not args.only:
        # Shuffle on full-refresh so a block doesn't always strike the same
        # paper. --only and --limit stay deterministic for repeatability.
        random.shuffle(pubs)

    now = dt.datetime.now(dt.timezone.utc)
    max_age = dt.timedelta(days=args.max_age_days) if args.max_age_days > 0 else None

    n_updated = n_unchanged = n_skipped = n_failed = n_zero = n_fresh = 0
    blocked = False

    for i, pub in enumerate(pubs):
        doi_raw = pub.get("doi", "")
        doi = normalize_doi(doi_raw)
        title = pub.get("title", "")
        year = pub.get("year")

        if not doi:
            print(f"[skip] (no DOI)                              {title[:60]}")
            n_skipped += 1
            continue

        # Forthcoming papers ARE attempted: working-paper cites are exactly
        # where Scholar > OpenAlex. The verify_match() guard (title sim + year
        # ±1 + DOI cross-check) is strict enough to reject wrong matches.

        # Freshness skip: if we have a recent good fetch for this DOI and
        # it isn't flagged, don't re-query Scholar. Saves the request budget
        # for stale + flagged papers. Disable with --max-age-days 0.
        if max_age is not None and doi not in flagged:
            existing_entry = counts.get(doi) or {}
            ts = existing_entry.get("fetched_at") if isinstance(existing_entry, dict) else None
            if ts:
                try:
                    fetched = dt.datetime.fromisoformat(ts)
                    age = now - fetched
                    if age < max_age:
                        print(f"[fresh] {doi:<40} (fetched {age.days}d ago, < {args.max_age_days}d)")
                        n_fresh += 1
                        continue  # no Scholar call, no jitter, no write needed
                except (ValueError, TypeError):
                    pass

        author_last = first_author_last_name(pub.get("authors", []))
        query = f"{title} {author_last}".strip()

        matched = None
        matched_sim = None
        last_reason = "no Scholar results"
        try:
            results = scholarly.search_pubs(query)
            for _ in range(MAX_SCHOLAR_HITS):
                candidate = next(results, None)
                if candidate is None:
                    break
                ok, reason, sim = verify_match(title, year, doi, candidate)
                if ok:
                    matched = candidate
                    matched_sim = sim
                    break
                last_reason = reason
        except MaxTriesExceededException:
            print(f"[BLOCKED] Scholar blocked the IP at paper #{i+1} ({doi}).")
            print(f"          {n_updated} updated, {n_unchanged} unchanged before block.")
            print(f"          Wait 24h or switch networks and re-run.")
            blocked = True
            break
        except Exception as e:
            print(f"[fail] {doi:<40} ({type(e).__name__}: {e})")
            n_failed += 1
            continue

        if matched is None:
            # No valid match in MAX_SCHOLAR_HITS. Existing count (if any)
            # is preserved; we just flag for manual review and skip the write.
            print(f"[fail] {doi:<40} ({last_reason}) — flagged for review")
            flagged[doi] = f"no match in {MAX_SCHOLAR_HITS} hits: {last_reason}"
            n_failed += 1
        else:
            new_count = matched.get("num_citations")
            if new_count is None:
                print(f"[fail] {doi:<40} (no num_citations field) — flagged for review")
                flagged[doi] = "Scholar result had no num_citations field"
                n_failed += 1
            elif int(new_count) == 0:
                # Scholar = 0 is almost always a junk-stub false positive
                # (metadata-corrupt entry that happened to pass verify_match).
                # Don't write; flag for review; let frontend fall back to OpenAlex.
                # Any prior count is preserved untouched.
                print(f"[zero] {doi:<40} Scholar=0 — flagged for review, OpenAlex will fill in")
                flagged[doi] = "Scholar returned 0 cites — likely metadata-poor match; verify manually"
                n_zero += 1
            else:
                old = counts.get(doi, {}).get("count") if isinstance(counts.get(doi), dict) else None
                arrow = f"{old} → {new_count}" if old is not None else f"{new_count}"
                print(f"[ok]   {doi:<40} {arrow}   (match {matched_sim:.2f})")
                counts[doi] = {
                    "count": int(new_count),
                    "title_match": round(matched_sim, 3),
                    "fetched_at": now.isoformat(timespec="seconds"),
                }
                # Confident match → clear any stale flag.
                flagged.pop(doi, None)
                if old == new_count:
                    n_unchanged += 1
                else:
                    n_updated += 1

        # Persist after every paper, regardless of outcome — protects against block mid-run.
        if not args.dry_run and i < len(pubs) - 1:
            atomic_write_yaml(build_payload(counts, flagged))

        # Jitter (skip on the last paper)
        if not args.no_jitter and i < len(pubs) - 1:
            delay = random.uniform(JITTER_MIN_SEC, JITTER_MAX_SEC)
            time.sleep(delay)

    # Final write
    if not args.dry_run:
        atomic_write_yaml(build_payload(counts, flagged))
        print(f"\nWrote {OUT_FILE.relative_to(ROOT)}")

    print(
        f"\nSummary: {n_updated} updated, {n_unchanged} unchanged, "
        f"{n_fresh} fresh-skipped, "
        f"{n_zero} Scholar=0 (flagged), {n_skipped} skipped, {n_failed} failed (flagged)."
    )
    if flagged:
        print(f"\n{len(flagged)} paper(s) flagged for manual review — see "
              f"`flagged_for_review:` section of {OUT_FILE.relative_to(ROOT)}.")
    if blocked:
        print("Run was interrupted by a Scholar block; partial progress preserved.")
        return 2
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, help="Only attempt first N publications (deterministic order).")
    ap.add_argument("--only", type=str, help="Only attempt a single DOI.")
    ap.add_argument("--dry-run", action="store_true", help="Fetch but don't write.")
    ap.add_argument("--no-jitter", action="store_true",
                    help=f"Disable {JITTER_MIN_SEC}-{JITTER_MAX_SEC} s sleep between papers (debugging only).")
    ap.add_argument("--max-age-days", type=int, default=DEFAULT_MAX_AGE_DAYS,
                    help=f"Skip papers whose count was fetched within the last N days "
                         f"(default {DEFAULT_MAX_AGE_DAYS}; 0 disables — refetch everything). "
                         f"Flagged papers are always re-queried regardless.")
    args = ap.parse_args()

    if not PUBS_FILE.exists():
        sys.exit(f"Missing {PUBS_FILE}")

    raise SystemExit(scrape(args))


if __name__ == "__main__":
    main()
