#!/usr/bin/env python3
"""
One-time bootstrap: walk the author's Scholar profile and build a
DOI → scholar_pub_id mapping in _data/scholar_pub_ids.yml.

With this mapping, scripts/fetch_scholar_counts.py can fetch counts via
direct per-paper citation URLs (much lighter rate-limit category than
search queries), dramatically reducing the chance of IP blocks.

Usage:
    .venv-scholar/bin/python scripts/fetch_scholar_pub_ids.py
    .venv-scholar/bin/python scripts/fetch_scholar_pub_ids.py --dry-run

Re-run only when new papers are added to publications.yml or your Scholar
profile gets restructured. Otherwise the mapping is stable.

Network cost: typically 1-3 Scholar requests total (one profile fetch,
possibly paginated). Compare to 39+ search queries on every count refresh
under the old scheme.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
import tempfile
from pathlib import Path

# Reuse helpers from the main scraper.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_scholar_counts import (  # noqa: E402
    normalize_doi,
    normalize_title,
    title_ratio,
)

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing. Run: ./scripts/setup_scholar.sh")

try:
    from scholarly import scholarly
    from scholarly._navigator import MaxTriesExceededException
except ImportError:
    sys.exit("scholarly missing. Run: ./scripts/setup_scholar.sh")


ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = ROOT / "_config.yml"
PUBS_FILE = ROOT / "_data" / "publications.yml"
OUT_FILE = ROOT / "_data" / "scholar_pub_ids.yml"

# Title similarity threshold for DOI ↔ profile-pub matching. Stricter than
# the main scraper's lenient floor because we're matching within a small
# closed set (just your own profile), not the entire Scholar corpus, so
# false-positive risk is much lower and we can afford precision.
TITLE_MATCH_THRESHOLD = 0.85


def read_scholar_user_id() -> str:
    """Pull scholar_userid out of _config.yml without a full Liquid parse."""
    with CONFIG_FILE.open() as f:
        for line in f:
            line = line.strip()
            if line.startswith("scholar_userid:"):
                # Format: 'scholar_userid: VwQmUFQAAAAJ # comment'
                value = line.split(":", 1)[1].strip()
                value = value.split("#", 1)[0].strip().strip('"').strip("'")
                if value:
                    return value
    sys.exit(f"Could not find 'scholar_userid:' in {CONFIG_FILE}")


def atomic_write_yaml(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(
            "# Auto-generated by scripts/fetch_scholar_pub_ids.py. Edit via the script, not by hand.\n"
        )
        yaml.safe_dump(
            payload,
            tmp,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=120,
        )
        tmp_path = tmp.name
    os.replace(tmp_path, path)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true",
                    help="Fetch the profile and print the mapping, but don't write the YAML.")
    args = ap.parse_args()

    user_id = read_scholar_user_id()
    print(f"Scholar user ID: {user_id}")

    with PUBS_FILE.open() as f:
        pubs = yaml.safe_load(f) or []
    print(f"Local publications: {len(pubs)}")

    print("Fetching Scholar profile (1-3 requests) …")
    try:
        author = scholarly.search_author_id(user_id)
        scholarly.fill(author, sections=["publications"])
    except MaxTriesExceededException:
        sys.exit("[BLOCKED] Scholar blocked the IP during profile fetch. "
                 "Wait 12-24 h and retry.")
    except Exception as e:
        sys.exit(f"[error] {type(e).__name__}: {e}")

    scholar_pubs = author.get("publications") or []
    print(f"Scholar profile publications: {len(scholar_pubs)}")
    print()

    # Match each YAML pub to its best Scholar entry by title similarity.
    pub_ids: dict[str, str] = {}
    unmatched: list[tuple[str, str, float]] = []  # (doi, title, best_sim)

    for our in pubs:
        doi = normalize_doi(our.get("doi", ""))
        title = our.get("title", "") or ""
        if not doi or not title:
            continue

        best_sim = 0.0
        best_pub = None
        best_title = ""
        for sp in scholar_pubs:
            bib = sp.get("bib", {}) or {}
            sp_title = bib.get("title", "") or ""
            sim = title_ratio(title, sp_title)
            if sim > best_sim:
                best_sim = sim
                best_pub = sp
                best_title = sp_title

        if best_pub is not None and best_sim >= TITLE_MATCH_THRESHOLD:
            pub_id = best_pub.get("author_pub_id")
            if pub_id:
                pub_ids[doi] = pub_id
                print(f"[ok]   {doi:<40} ↔ {pub_id}  (sim {best_sim:.2f})")
            else:
                print(f"[fail] {doi:<40} (matched but no author_pub_id field)")
                unmatched.append((doi, title, best_sim))
        else:
            print(f"[fail] {doi:<40} (best sim {best_sim:.2f} < {TITLE_MATCH_THRESHOLD}: {best_title[:50]!r})")
            unmatched.append((doi, title, best_sim))

    print()
    print(f"Matched: {len(pub_ids)} / {len(pubs)}")
    if unmatched:
        print(f"Unmatched: {len(unmatched)} — these will fall back to search-based fetching.")

    payload = {
        "fetched_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "scholar_user_id": user_id,
        "pub_ids": {k: pub_ids[k] for k in sorted(pub_ids)},
    }

    if args.dry_run:
        print()
        print("--- dry-run YAML preview ---")
        print(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False))
    else:
        atomic_write_yaml(OUT_FILE, payload)
        print(f"Wrote {OUT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
